# Generated by Django 3.0.3 on 2020-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('microcontroller', models.CharField(max_length=200)),
                ('operating_voltage', models.IntegerField()),
                ('input_voltage', models.IntegerField()),
                ('input_voltage_limits', models.IntegerField()),
                ('digital_inputOutput_pins', models.IntegerField()),
                ('analog_pins', models.IntegerField()),
                ('dc_current_per_inputOutput_pins', models.IntegerField()),
                ('flash_memory', models.IntegerField()),
                ('SRAM', models.IntegerField()),
                ('clock_speed', models.IntegerField()),
                ('typee', models.CharField(max_length=200)),
            ],
        ),
    ]
