# Generated by Django 3.0.3 on 2020-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200814_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='input_voltage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='input_voltage_limits',
            field=models.CharField(max_length=200),
        ),
    ]
