# Generated by Django 3.0.3 on 2020-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200814_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller',
            name='photo_main',
            field=models.ImageField(default='blank', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
