# Generated by Django 3.0.3 on 2020-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_microcontroller_list_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('speed', models.CharField(max_length=200)),
                ('voltage_range', models.CharField(max_length=200)),
                ('typee', models.CharField(max_length=200)),
                ('no_load_current', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
