# Generated by Django 3.0.8 on 2020-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='photo_main',
            field=models.ImageField(default='blank', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
