# Generated by Django 3.0.8 on 2020-08-14 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_motor_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
