# Generated by Django 3.0.8 on 2020-08-14 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_motor_list_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('led_size', models.IntegerField()),
                ('wavelength', models.IntegerField()),
                ('max_forward_current', models.IntegerField()),
                ('waat', models.IntegerField()),
                ('operating_temperature_range', models.CharField(max_length=200)),
                ('storage_temperature_range', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(default='blank', upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
