# Generated by Django 3.0.8 on 2020-08-17 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_led'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('operating_voltage_range', models.CharField(max_length=200)),
                ('level_output', models.CharField(max_length=200)),
                ('delay_time', models.CharField(max_length=200)),
                ('operation_temperature', models.CharField(max_length=200)),
                ('Range', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('pressure_range', models.CharField(blank=True, max_length=200)),
                ('temperature_accuracy', models.CharField(blank=True, max_length=200)),
                ('diameter', models.CharField(blank=True, max_length=200)),
                ('length', models.CharField(blank=True, max_length=200)),
                ('switch_life_span', models.CharField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(default='blank', upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
